### ISSUE TITLE
Good Luck w/ Project

### ISSUE THREAD

**Issue by MasonBurdette** [lurquhar1221/OpenSlither#1]
Are you still working on this project, or is it abandoned? I'm working on a client-side implementation, but would love to help with a server-side one.  If you look in game[version].js you can see all the packets being sent to the server. Also you can connect to another server by changing where it makes the new WebSocket. Good luck with this project anyways, I might contribute once it gets started!

Skype - masonburdette@outlook.com

**Comment by lurquhar1221** [comment]
Still working on it (not abandoned!)
Resolving issue
